import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const commonStyles = StyleSheet.create({
  column: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  row: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  colorPrimary: { color: colors.primary },
  noPadding: { padding: 0 },
  noMargin: { margin: 0 },
  margin: { margin: 15 },
  marginTop: { marginTop: 15 },
  marginLeft: { marginLeft: 15 },
  marginRight: { marginRight: 15 },
  headerText: {
    paddingTop: 10,
    fontSize: 20,
    fontWeight: "bold",
  },
  directionRow: { flexDirection: "row" },
  directionColumn: { flexDirection: "column" },
  centerText: { textAlign: "center" },
  alarmText: { color: "red", fontWeight: "bold" },
  fullHeight: { minHeight: "100%" },
  fullWidth: { minWidth: "100%" },
  fullWidthAndHeight: { width: "100%", height: "100%" },
  height100pc: { height: "100%" },
  absolute: { position: "absolute" },
  spaceEvenly: { justifyContent: "space-evenly" },
  spaceBetween: { justifyContent: "space-between" },
  justifyContentStart: { justifyContent: "flex-start" },
  justifyContentCenter: { justifyContent: "center" },
  justifyContentEnd: { justifyContent: "flex-end" },
  flexWrap: { flexWrap: "wrap" },
  flexThree: { flex: 3 },
  flexTwo: { flex: 2 },
  flexOne: { flex: 1 },
  flexHalf: { flex: 0.5 },
  flexZero: { flex: 0 },
  centeredRow: { flexDirection: "row", justifyContent: "center" },
  centerAlignedRow: { flexDirection: "row", alignItems: "center" },
  bold: { fontWeight: "bold" },
  centeredText: { textAlign: "center" },
  textAlignRight: { textAlign: "right" },
  alignItemsStart: { alignItems: "flex-start" },
  alignItemsCenter: { alignItems: "center" },
  alignItemsEnd: { alignItems: "flex-end" },
  alignSelfCenter: { alignSelf: "center" },
  fontItalic: { fontStyle: "italic" },
  inlineCardTitle: {
    fontWeight: "bold",
  },
  inlineCardSubtitle: {
    fontSize: 12,
    fontWeight: "normal",
  },
  smallText: {
    fontSize: 12,
  },
  smallTitle: {
    fontSize: 14,
  },
  pageTitle: {
    fontSize: 16,
    fontWeight: "600",
  },
  darkerDivide: { borderBottomColor: "lightgray", borderBottomWidth: 1 },
  hyperLink: {
    color: "blue",
    textDecorationColor: "blue",
    textDecorationLine: "underline",
  },
  underline: { textDecorationLine: "underline" },
  oneThirdMaxWidth: { maxWidth: "33.333333%" },
  backgroundWhite: { backgroundColor: "white" },
  compactPadding: { paddingVertical: 2, paddingHorizontal: 5 },
});
