name: "Moropo - Trigger Mobile App Test Run"
description: "Uses Moropo.com to execute a mobile app UI test"
inputs:
  scheduled_test_id:
    description: "Moropo Scheduled Test ID - find this in your scheduled test setup wizard"
    required: true
  app_secret:
    description: "Moropo App Secret Key - find this in your app in the Moropo dashboard"
    required: true
  expo_release_channel:
    description: "Expo Release Channel (optional) - requires Moropo-Expo integration setup. Tell Moropo to pull a new Expo update for this test run."
    required: false
  build_input:
    description: "Blob or URL (optional) - app product from another action or download URL to override the App Build to test with."
runs:
  using: "docker"
  image: "Dockerfile"
