name: Moropo Test Run
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
  checks: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Moropo Tests
        uses: ./moropo_gha/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scheduled_test_id: 53d3f340-f606-404a-9bc5-6d2e7e509b3f
          app_secret: ${{ secrets.MOROPO_API_KEY }}
