name: Moropo Test Run
on: pull_request
permissions:
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Moropo Tests
        uses: moropo-com/action-trigger-test-run@master
        with:
          moropo_url: https://test.moropo.com/
          moropo_api_url: https://api.test.moropo.com/
          #scheduled_test_id: 8e2cb181-257a-40b7-8f55-56a5b5d182d7 #Android
          scheduled_test_id: 53d3f340-f606-404a-9bc5-6d2e7e509b3f #iOS
          api_key:  5871aabf-ff92-4a5d-977f-dbae5bab5a08 #f81ba9de-7a49-4f04-a907-f27ca83b886a
          sync: true
          env: '{"EXPORELEASECHANNEL":"fake link","VAR_1":"variable value"}'
          ##expo_release_channel: https://u.expo.dev/cd0e344b-8011-4434-91a6-dec86deb68c0?channel-name=moropo-410&runtime-version=exposdk:47.0.0&platform=android&disableOnboarding=1
          #build_path: builds/ios.app.zip
