name: Moropo Test Run
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Moropo Tests
        uses: moropo-com/action-trigger-test-run@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scheduled_test_id: 53d3f340-f606-404a-9bc5-6d2e7e509b3f
          app_secret: ${{ secrets.MOROPO_API_KEY }}
          expo_release_channel: https://u.expo.dev/cd0e344b-8011-4434-91a6-dec86deb68c0?channel-name=moropo-430&runtime-version=exposdk:47.0.0&platform=android&disableOnboarding=1
