name: Moropo Test Run
on: pull_request
permissions:
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Moropo Tests
        uses: moropo-com/action-trigger-test-run@staging
        with:
          scheduled_test_id: ec3972e0-4c27-4b8f-ac82-fd8904d24103
          api_key: 5fa99ae0-99c1-49d7-a9de-e34def35aa95
          #expo_release_channel: https://u.expo.dev/cd0e344b-8011-4434-91a6-dec86deb68c0?channel-name=moropo-410&runtime-version=exposdk:47.0.0&platform=android&disableOnboarding=1
