name: Moropo Test Run
on: pull_request
permissions:
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip Files
        run: |
          zip -r tests.zip tests/ -x ".git/*" ".github/*"
          ls -l
      #- name: Upload Tests
      #  run: |
      #    curl -X POST https://api.test.moropo.com/apps/upload-tests \
      #    -H "x-app-api-key:  78c5b68c-451f-4973-aa77-8db81078caad" \
      #    -H "x-merge-strategy: changes_only" \
      #    -H "x-branch-name: main" \
      #    -F tests=@tests.zip
      - name: Run Moropo Tests
        uses: moropo-com/action-trigger-test-run@master
        with:

          #dev
          #moropo_url: https://dev.moropo.com/
          #moropo_api_url: https://api.dev.moropo.com/
          #api_key:  ac92a20f-6bef-4c39-8666-74927b604f61
          #scheduled_test_id: fe63bbda-d61b-4be2-9053-00deca7cea98 #Android
          #scheduled_test_id: #iOS

          #staging
          moropo_url: https://test.moropo.com/
          moropo_api_url: https://api.test.moropo.com/
          api_key: 6c4d7baf-e152-4aeb-a7e4-8b69147adbf2 #staging
          #scheduled_test_id: 8e2cb181-257a-40b7-8f55-56a5b5d182d7 #Android
          scheduled_test_id: 53d3f340-f606-404a-9bc5-6d2e7e509b3f #iOS 

          #prod
          #moropo_url: https://app.moropo.com/
          #moropo_api_url: https://api.moropo.com/
          #api_key: 0d8460de-abb1-4574-acc4-f266e1f899ee #Classy Mall
          #scheduled_test_id: 04f1acb4-c4d5-4389-b31e-55002a2ae059 #Android 
          #api_key: b97029c8-8ee1-44cc-88cc-83d6058a4597
          #scheduled_test_id: 5f609bd9-e0fc-431b-8849-e74166a538d7

          #github_token: ${{ secrets.TB_GITHUB_TOKEN }}
          #tags: '["demo"]'
          sync: true
          #env: '{"EXPORELEASECHANNEL":"https://u.expo.dev/cd0e344b-8011-4434-91a6-dec86deb68c0?channel-name=moropo-555&runtime-version=exposdk:47.0.0&platform=ios","VAR_1":"newVar"}'
          #env: '{"EXPORELEASECHANNEL":"FAKE","VAR_1":"newVar"}'
          #expo_release_channel: https://u.expo.dev/cd0e344b-8011-4434-91a6-dec86deb68c0?channel-name=moropo-410&runtime-version=exposdk:47.0.0&platform=android&disableOnboarding=1
          build_path: builds/ios.app.zip
          #build_path: builds/app-debug.apk
