name: Moropo Test Run
on: pull_request
permissions:
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Moropo Tests
        uses: moropo-com/action-trigger-test-run@v1.0.2
        with:
          scheduled_test_id: 53d3f340-f606-404a-9bc5-6d2e7e509b3f
          app_secret: ${{ secrets.MOROPO_API_KEY }}
          
