name: "PR: Test"

on:
  pull_request:
    branches:
      - GH-action-moropo-test
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "assets/**"

jobs:
  Moropo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Post/Edit Comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Sending a test request to Moropo for commit ${{ github.sha }}... this may take a few minutes"
          comment_includes: "test request"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Test Request to Moropo
        run: |
          curl --request POST \
          --url http://moropo.netlify.app/.netlify/functions/scheduleTestRun \
          --header 'content-type: application/json' \
          --header 'x-moropo-api-key: ${{ secrets.MOROPO_API_KEY }}' \
          --header 'x-moropo-app-id: ${{ secrets.MOROPO_APP_ID }}' \
          --header 'x-moropo-origin: ${{ github.event.pull_request.url}}' \
          --header 'x-moropo-devclient: https://expo.dev/accounts/morrowdigital/projects/classy-mall/builds/0f64dd34-422a-4c93-a889-8aef050e8a31'

      - name: Failed to send request
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Something went wrong sending a test request to Moropo for commit ${{ github.sha }}"
          comment_includes: "test request"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Successfully sent test request
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "A test request was successfully sent to Moropo for commit ${{ github.sha }}!"
          comment_includes: "test request"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
